"""
Django settings for aps_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_qeonk5bl6ltuk2l0h2s+h7!mi&k(vg7#chl*m!+2p=!f685j*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Dev: permissive so the Cloudflare tunnel host resolves. Lock down for prod.
ALLOWED_HOSTS = ['*']

# Cloudflare quick tunnels hand out a new *.trycloudflare.com host each start;
# trusting the wildcard lets CMS login + the contact form (CSRF-protected POSTs)
# work through any tunnel URL with zero further edits.
CSRF_TRUSTED_ORIGINS = [
    'https://*.trycloudflare.com',
    'https://*.ngrok-free.app',
    'https://*.ngrok.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.dev',
    'https://*.pythonanywhere.com',  # free test deploy for the client
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # APS apps (backend under the designer's static pages)
    'core',
    'pages',
    'divisions',
    'faq',
    'submissions',
    'cmsadmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.MaintenanceMiddleware',
]

ROOT_URLCONF = 'aps_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_globals',
                'core.context_processors.page_content',
                'core.context_processors.cms_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'aps_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

# MySQL (MariaDB 11.4) — utf8mb4 end-to-end for Arabic content.
# Credentials default to the dev values but can be overridden via environment
# variables. PRODUCTION HARDENING: move APS_DB_PASSWORD out of source entirely
# (env/.env/secret manager) and rotate this generated dev password.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('APS_DB_NAME', 'aps_db'),
        'USER': os.environ.get('APS_DB_USER', 'aps_user'),
        'PASSWORD': os.environ.get('APS_DB_PASSWORD', 'wLjozlv2cAsGkDHMNa687lgy'),
        'HOST': os.environ.get('APS_DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('APS_DB_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Rollback: SQLite snapshot kept at db.sqlite3.backup + data_backup.json.
# To revert, swap ENGINE back to django.db.backends.sqlite3 / NAME db.sqlite3.


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# His assets live here during dev; collectstatic targets STATIC_ROOT for prod.
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User uploads (media library, CV files, etc.) — wired in later phases.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CMS image uploads can be a few MB. Django rejects a request body larger than
# DATA_UPLOAD_MAX_MEMORY_SIZE (2.5 MB default) — which used to fail the brand
# logo / footer-image save with a generic "couldn't save" toast. The store now
# uploads images as multipart FILE parts (exempt from this cap), but we raise the
# limits anyway so the JSON fallback and the full-tree store save never hit it.
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024   # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024   # 25 MB

# CMS admin auth
LOGIN_URL = '/cms/login/'
LOGIN_REDIRECT_URL = '/cms/'

# Email — used to send the password-reset code (forgot-password flow).
# Set APS_SMTP_USER + APS_SMTP_PASSWORD (e.g. a Gmail address + App Password) to
# deliver real emails. Until they're set, codes are printed to the server
# console (so the flow is fully testable without SMTP).
EMAIL_HOST = os.environ.get('APS_SMTP_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('APS_SMTP_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('APS_SMTP_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('APS_SMTP_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('APS_SMTP_FROM', EMAIL_HOST_USER or 'APS CMS <no-reply@aps-sa.com>')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
