# Generated by Django 5.2.15 on 2026-06-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary', models.CharField(default='#558BAD', max_length=9)),
                ('color_accent', models.CharField(default='#1A6DA2', max_length=9)),
                ('color_hover', models.CharField(default='#477694', max_length=9)),
                ('color_text', models.CharField(default='#0B1220', max_length=9)),
                ('color_muted', models.CharField(default='#475569', max_length=9)),
                ('color_bg', models.CharField(default='#F7FAFC', max_length=9)),
                ('color_footer', models.CharField(default='#263F4E', max_length=9)),
                ('logo', models.CharField(blank=True, default='', max_length=300)),
                ('arabic_font', models.CharField(default='Cairo', max_length=80)),
                ('english_font', models.CharField(default='Inter', max_length=80)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.CharField(help_text='Static-relative path, e.g. assets/images/clinets/audica 1.png', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(default='', max_length=200)),
                ('site_name_ar', models.CharField(default='', max_length=200)),
                ('tagline_en', models.CharField(default='', max_length=300)),
                ('tagline_ar', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address_en', models.CharField(default='', max_length=300)),
                ('address_ar', models.CharField(default='', max_length=300)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Static path under assets/images/icons/, e.g. linkedin.svg', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
