# Generated by Django 5.2.15 on 2026-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('label_en', models.CharField(default='', max_length=120)),
                ('label_ar', models.CharField(default='', max_length=120)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
