# Generated by Django 5.2.15 on 2026-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
