# Generated by Django 5.2.15 on 2026-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_footer',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
