# Generated by Django 5.2.15 on 2026-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='font_scale',
            field=models.CharField(default='md', max_length=8),
        ),
        migrations.AddField(
            model_name='brand',
            name='theme',
            field=models.CharField(default='aps', max_length=40),
        ),
    ]
