# Generated by Django 5.2.15 on 2026-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_font_scale_brand_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cms_theme',
            field=models.CharField(default='aps', max_length=40),
        ),
    ]
