# Generated by Django 5.2.15 on 2026-06-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(default='', max_length=200)),
                ('title_ar', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('seo_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('seo_title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('seo_desc_en', models.TextField(blank=True, default='')),
                ('seo_desc_ar', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
