# Generated by Django 5.2.15 on 2026-06-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('banner_subtitle_en', models.CharField(blank=True, default='', max_length=200)),
                ('banner_subtitle_ar', models.CharField(blank=True, default='', max_length=200)),
                ('about_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('about_title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('about_body_en', models.TextField(blank=True, default='')),
                ('about_body_ar', models.TextField(blank=True, default='')),
                ('systems_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('systems_title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('systems_subtitle_en', models.CharField(blank=True, default='', max_length=300)),
                ('systems_subtitle_ar', models.CharField(blank=True, default='', max_length=300)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=60)),
                ('contact_website', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivisionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(help_text='Static-relative path, e.g. assets/images/divisions/sps/projects/p1.jpg', max_length=300)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('location_en', models.CharField(blank=True, default='', max_length=120)),
                ('location_ar', models.CharField(blank=True, default='', max_length=120)),
                ('typology_en', models.CharField(blank=True, default='', max_length=120)),
                ('typology_ar', models.CharField(blank=True, default='', max_length=120)),
                ('installed_power_en', models.CharField(blank=True, default='', max_length=120)),
                ('installed_power_ar', models.CharField(blank=True, default='', max_length=120)),
                ('contract_en', models.CharField(blank=True, default='', max_length=120)),
                ('contract_ar', models.CharField(blank=True, default='', max_length=120)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='divisions.division')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
