# Generated by Django 5.2.15 on 2026-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='cms_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
