# Generated by Django 5.2.15 on 2026-06-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_division_cms_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', help_text='Static-relative path, e.g. assets/images/icons/sys/sps-1.svg', max_length=300)),
                ('title_en', models.CharField(blank=True, default='', max_length=300)),
                ('title_ar', models.CharField(blank=True, default='', max_length=300)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_ar', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='divisions.division')),
            ],
            options={
                'ordering': ['section_key', 'order', 'id'],
            },
        ),
    ]
